### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Thefluffypvper1** [777Ricky/DomainTracker#1]
IP limit per Ip address, this would be usefull to know how many "legit" player joins there are so it would exclude alts filling up numbers and could confuse server owner into thinking its real players joining but 100 of those joins where alts.

**Comment by 777Ricky** [comment]
> IP limit per Ip address, this would be usefull to know how many "legit" player joins there are so it would exclude alts filling up numbers and could confuse server owner into thinking its real players joining but 100 of those joins where alts.

I thought about adding some kind of feature like this my only problem is I think I would need to store player IP addresses in order to effectively achieve this and I'm not really too fond of storing that but maybe I could make it an optional feature toggled off by default
